### ISSUE TITLE
Can't download Wind Integration National Dataset

### ISSUE THREAD

**Issue by Neo-101** [oshapio/Localized-CNNs-for-Geospatial-Wind-Forecasting#2]
Thanks for the open-source code. When I click the link of Wind Integration National Dataset (WIND) in README, it leads me to a zip file, not a website where I can choose the area like the picture shows. It seems that WIND is no longer in service.

Can you upload the processed "WINDS_processed_data.pkl" to this repo, please? I am interested in the first case study on real-world data. Thank you very much.

**Comment by oshapio** [comment]
Thanks for bringing this issue forward!

Indeed, it seems like getting the WIND from source is not (straightforwardly?) possible at the current time. As per your suggestion, I uploaded the processed "WINDS_processed_data.pkl" file (available [here](https://drive.google.com/file/d/12HwT8LbltjJZyI1HMKqCLjvxS6nWnHIN/view?usp=share_link)), but I also uploaded the raw files (available [here](https://drive.google.com/drive/folders/1wrstzG00J056llcqrg-jpFpABR2EvlWJ?usp=share_link)) which can then be processed into the pickled version (this is the recommended route for dealing with untrusted files). 

I double-checked and the experiments seem to run correctly. Goodluck!
